### ISSUE TITLE
Two CSV files are missing

### ISSUE THREAD

**Issue by ChAdilHussainGujjar** [Tungom/EV_Infrastructure_Optimization#1]
These 2 csv files are missing in the code. can you please share these files?
EVinfrastructureZero.csv
SupplyPointsDistanceMatrix.csv

**Comment by Tungom** [comment]
Thanks for bringing that to my attention. I have added a folder called [ESWA_Code_Submission](https://github.com/Tungom/EV_Infrastructure_Optimization/tree/main/ESWA_Code_Submission) in the repository. You can find the dataset there.

**Comment by dradilhussain** [comment]
Hey, I am facing the ModuleNotFoundError: No module named 'ortools
I have already installed the ortools, and i checked it is installed, version 9.7.2996, but still it says the same ModuleNotFoundError

**Comment by Tungom** [comment]
Add a cell in the beginning of the Jupyter notebook and in the cell add the below code and run for installations. Let me know if it works 

!pip install pandas
!pip install scipy
!pip install numpy
!pip install sklearn
!pip install ortools==9.4.1874
!pip install pulp
!pip install k-means-constrained>=0.7.2

**Comment by dradilhussain** [comment]
yes it worked now,
I face an error in Cell 33, line 15
TypeError: 'float' object cannot be interpreted as an integer

**Comment by Tungom** [comment]
can you send the screenshot of the cell and error. OR you can check to ensure that the datatypes used are consistent.

**Comment by dradilhussain** [comment]
here it is.
<img width="924" alt="Screenshot 2023-10-11 at 01 13 42" src="https://github.com/Tungom/EV_Infrastructure_Optimization/assets/69067321/365c1f3a-aa42-4e4d-a1d7-39c3bc273292">

**Comment by Tungom** [comment]
Got it. unfortunately I do not encounter this error on my local run. It is a problem with a datatype which is supposed to be an int but is a float. look into the variables profits, weight and capacities to see which you need to asjust. you can also take a look at the googleORtools API.

**Comment by dradilhussain** [comment]
I tried, but couldn't understand where exactly I needed to fix it.
Can you please try if it is possible?
